FROM eclipse-temurin:17

LABEL maintainer = "shambhavik24"

WORKDIR /app

COPY target/fileconversion-0.0.1-SNAPSHOT.jar  /app/fileconversion.jar


ENTRYPOINT ["java", "-jar", "fileconversion.jar"]

